language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
  - composer install --dev --no-interaction

script:
  - phpunit --coverage-clover clover.xml --configuration phpunit.xml
